server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:mysql://localhost:3306/test   # 数据库连接URL
    username: root                   # 数据库用户名
    password: root                    # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动类
  redis:
    host: localhost
    port: 6379
    password: foobared
jwt:
  secret: owS6umB00tFEv/V2XxDOrLQRZeA57KZ5U1RRdkkAckXwiUK7qtWS7haEBRfm5N9AwismDw9Pwf7PvntlTd2P6w==
  expiration: 86400000
logging:
  level:
    org.springframework: DEBUG
    com.example: DEBUG
